function comparisonData(){return [
{title:'What is the primary unit?',icon:'◫',ios:'An application and the documents it owns.',android:'An application, activity/service and content provider.',agent:'A person, project, task, document, event, place, message, device or agent is a durable system entity.'},
{title:'Who owns the data model?',icon:'◇',ios:'Mostly each app and its cloud service.',android:'Mostly each app/provider, mixed with vendor services.',agent:'Local system authority with explicit providers, provenance and portable schemas.'},
{title:'How are actions exposed?',icon:'⌘',ios:'App Intents, Shortcuts and selected frameworks.',android:'Intents, AppFunctions and heterogeneous APIs.',agent:'One typed action/provider catalog shared by UI, CLI, scripts and agents.'},
{title:'What is history?',icon:'◌',ios:'Per-app state, backups and limited system recents.',android:'Per-app state, notifications, backups and activity history.',agent:'A semantic event log with source, authority, effect, undo or compensation.'},
{title:'How do agents act?',icon:'◎',ios:'Assistant over capabilities explicitly exposed by apps.',android:'Assistant over intents, screens and emerging app functions.',agent:'Inspectable plans, scoped capabilities, shadow/dry-run modes and execution receipts.'},
{title:'How is UI composed?',icon:'⌁',ios:'Highly polished but mostly fixed app-owned surfaces.',android:'Flexible ecosystem, still predominantly app-owned surfaces.',agent:'Malleable views, transclusion, structured copy and reusable interaction contracts.'},
{title:'How portable is the platform?',icon:'↔',ios:'Vertically integrated Apple hardware.',android:'Broad hardware with vendor fragmentation.',agent:'Portable contracts above architecture ports, board packages and isolated user-space drivers.'},
{title:'What is open?',icon:'○',ios:'Proprietary platform and governance.',android:'Open base mixed with proprietary services and vendor layers.',agent:'Open native stack, public contracts and evidence-driven hardware routes.'}
]}
function compare(){nav('compare');const rows=comparisonData();app.innerHTML=`${workspaceHead('System-model comparison','iOS, Android, and Agent OS','A detailed comparison of architectural models. Agent OS entries describe the intended design and are not claims of completed implementation.')}<div class="compare-story"><section><span>iOS</span><strong>Vertically integrated app ecosystem</strong><p>Consistency and polish are obtained through tight control of hardware, frameworks, distribution and app boundaries.</p></section><section><span>Android</span><strong>Open platform with app and vendor layers</strong><p>Broad hardware reach and extensibility coexist with API fragmentation, vendor dependencies and application silos.</p></section><section class="agent"><span>Agent OS</span><strong>APP-LAST entity and action system</strong><p>Durable work objects, local authority, shared actions and inspectable agents are native system concepts.</p></section></div><div class="comparison-sections">${rows.map(r=>`<article class="comparison-block"><div class="comparison-question"><span>${r.icon}</span><h2>${esc(r.title)}</h2></div><div class="comparison-columns"><div><label>iOS</label><p>${esc(r.ios)}</p></div><div><label>Android</label><p>${esc(r.android)}</p></div><div class="agent"><label>Agent OS target</label><p>${esc(r.agent)}</p></div></div></article>`).join('')}</div><section class="section"><div class="section-head"><div class="eyebrow">The essential difference</div><h2>Agent OS changes the system model, not only the assistant.</h2><p>The key question is not whether the OS has AI, widgets or another sharing protocol. It is whether durable objects, actions, history and authority exist at system level or remain fragmented across applications.</p></div><div class="compare-flows"><div><strong>iOS / Android today</strong><span>Intent → choose app → navigate app state → perform operation → app-owned history</span></div><div class="agent"><strong>Agent OS target</strong><span>Intent → inspect entity context → preview typed action plan → capability check → receipt and semantic history</span></div></div></section>`}
const OS_LANDSCAPE=[
['Fuchsia','Production-oriented capability OS','Zircon, components, FIDL, drivers and update architecture. Strong prior art for capabilities and decomposition; not the Agent OS kernel or product model.','Capabilities · components · FIDL'],
['seL4','Formally verified microkernel','Exceptional assurance and minimal trusted computing base. Prior art for capability semantics and verification, but intentionally not a full mobile product stack.','Verification · TCB · capabilities'],
['Redox','Rust-first general-purpose OS','Useful experience in a Rust-native kernel/userspace ecosystem, scheme-based interfaces and incremental hardware support.','Rust · microkernel ideas · desktop'],
['Genode','Component framework and OS construction kit','Strong isolation, capability-based composition and multiple kernels. Relevant for component boundaries and controlled compatibility.','Components · capabilities · isolation'],
['postmarketOS','Mainline Linux mobile distribution','Broad device-porting knowledge and community hardware evidence. Keeps Linux/POSIX as substrate, unlike Agent OS native targets.','Mobile Linux · devices · mainline'],
['GrapheneOS','Hardened Android distribution','Security engineering, exploit mitigations and practical Pixel support. Remains Android-based and app-first.','Android hardening · Pixel · privacy'],
['Haiku','Coherent desktop OS','Demonstrates the value of consistent native APIs, integrated UX and long-lived system identity outside mainstream Unix desktops.','Coherence · native APIs · UX'],
['Plan 9 / Inferno','Everything as composable resources','Important prior art for namespaces, distributed resources and system-wide conceptual consistency.','Namespaces · distribution · simplicity']
];
function landscape(){nav('landscape');app.innerHTML=`${workspaceHead('Prior art made visual','Operating-system landscape','The projects that matter most to Agent OS, what they prove, and where the design deliberately diverges.')}<div class="landscape-map"><div class="axis y"><span>Product system</span><span>Kernel / mechanism</span></div><div class="axis x"><span>Compatibility-first</span><span>New native model</span></div><div class="landscape-points"><i style="--x:70%;--y:66%">Fuchsia</i><i style="--x:88%;--y:88%">seL4</i><i style="--x:72%;--y:80%">Redox</i><i style="--x:80%;--y:72%">Genode</i><i style="--x:26%;--y:42%">postmarketOS</i><i style="--x:16%;--y:48%">GrapheneOS</i><i style="--x:44%;--y:38%">Haiku</i><i class="agent" style="--x:88%;--y:20%">Agent OS</i></div></div><div class="landscape-grid">${OS_LANDSCAPE.map(x=>`<article><div class="eyebrow">${x[0]}</div><h2>${x[1]}</h2><p>${x[2]}</p><span class="pill">${x[3]}</span></article>`).join('')}</div><section class="section"><div class="section-head"><div class="eyebrow">Synthesis</div><h2>Take mechanisms, not inherited assumptions.</h2><p>Agent OS studies capability systems, verified kernels, mobile Linux, hardened Android and coherent native platforms, then evaluates each idea against an APP-LAST, local-first and agent-native product model.</p></div></section>`}